[project]
name = "bouncer"
version = "0.1.0"
description = "Bouncer screens iMessages for you, and lets you know when you get important ones."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "colorama>=0.4.6",
    "requests>=2.32.3",
]
